import React, { useState, useEffect } from "react";
import "../../assets/admin.css";
import "./css/receivemoney.css";
import axios from "axios";
import notificationService from '../../services/notificationService';
import balanceService from '../../services/balanceService';
import { broadcastFundTransaction } from '../../services/fundTransactionChannel';

const ReceiveMoney = () => {
  const [fundAccounts, setFundAccounts] = useState([]);
  const [amount, setAmount] = useState("");
  const [payerName, setPayerName] = useState("");
  const [receiptNo, setReceiptNo] = useState(""); // Will be auto-generated
  const [fundAccountId, setFundAccountId] = useState("");
  const [description, setDescription] = useState("");
  const [reference, setReference] = useState("");
  const [modeOfPayment, setModeOfPayment] = useState("Cash");
  const [message, setMessage] = useState("");
  const [successMessage, setSuccessMessage] = useState("");
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState({});
  
  // Modal states
  const [showFundAccountModal, setShowFundAccountModal] = useState(false);
  const [fundAccountSearch, setFundAccountSearch] = useState("");
  
  // Selected account details for display
  const [selectedFundAccount, setSelectedFundAccount] = useState(null);

  // Fetch fund accounts and recipient accounts
  useEffect(() => {
    const fetchFundAccounts = async () => {
      try {
        const token = localStorage.getItem('token');
        const response = await axios.get('/api/fund-accounts', {
          headers: {
            'Authorization': `Bearer ${token}`,
            'Content-Type': 'application/json'
          }
        });
        setFundAccounts(response.data);
      } catch (error) {
        console.error('Error fetching fund accounts:', error);
      }
    };

    fetchFundAccounts();
  }, []);

  // Auto-generate receipt numbers when any input is filled
  const [referenceNo, setReferenceNo] = useState("");
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  // Function to generate receipt numbers
  const generateReceiptNumbers = () => {
    if (!hasAutoGenerated) {
      const today = new Date();
      const dateStr = today.toISOString().slice(0, 10).replace(/-/g, '');
      const randomNum = Math.floor(Math.random() * 9999).toString().padStart(4, '0');
      const year = today.getFullYear();
      const yearRandomNum = Math.floor(Math.random() * 9999).toString().padStart(4, '0');
      
      setReceiptNo(`RCPT-${dateStr}-${randomNum}`);
      setReferenceNo(`COL-${year}-${yearRandomNum}`);
      setHasAutoGenerated(true);
    }
  };

  // Watch for any input changes to trigger auto-generation
  useEffect(() => {
    if (amount || payerName || fundAccountId || reference || description) {
      generateReceiptNumbers();
    }
  }, [amount, payerName, fundAccountId, reference, description, hasAutoGenerated]);

  // Validation function
  const validateForm = () => {
    const newErrors = {};
    
    if (!amount || parseFloat(amount) <= 0) {
      newErrors.amount = "Amount is required and must be greater than 0";
    }
    
    if (!payerName.trim()) {
      newErrors.payerName = "Payer name is required";
    }
    
    if (!fundAccountId) {
      newErrors.fundAccount = "Please select a fund account";
    }
    
    if (!modeOfPayment) {
      newErrors.modeOfPayment = "Payment mode is required";
    }
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  // Clear specific error when user starts typing
  const clearError = (field) => {
    if (errors[field]) {
      setErrors(prev => ({ ...prev, [field]: undefined }));
    }
  };

  // Handle fund account selection
  const handleFundAccountSelect = (account) => {
    setSelectedFundAccount(account);
    setFundAccountId(account.id.toString());
    setShowFundAccountModal(false);
    clearError('fundAccount');
  };

  // Filter accounts based on search
  const filteredFundAccounts = fundAccounts.filter(account =>
    account.name.toLowerCase().includes(fundAccountSearch.toLowerCase()) ||
    account.code.toLowerCase().includes(fundAccountSearch.toLowerCase())
  );

  // Reset form
  const resetForm = () => {
    setAmount("");
    setPayerName("");
    setDescription("");
    setReference("");
    setModeOfPayment("Cash");
    setSelectedFundAccount(null);
    setFundAccountId("");
    setErrors({});
    setMessage("");
    setSuccessMessage("");
    setReceiptNo("");
    setReferenceNo("");
    setHasAutoGenerated(false);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    // Validate form
    if (!validateForm()) {
      return;
    }
    setLoading(true);
    setMessage("");
    setSuccessMessage("");
    
    // Use the payer name entered by user
    const finalPayerName = payerName.trim();
    
    try {
      const token = localStorage.getItem('token');
      const transactionData = {
        type: "Collection",
        amount: parseFloat(amount),
        description: description.trim() || null,
        recipient: finalPayerName,
        department: "General", // Default value since field is required
        category: "Revenue Collection", // Default value since field is required
        reference: reference.trim() || null,
        fund_account_id: fundAccountId ? parseInt(fundAccountId) : null,
        mode_of_payment: modeOfPayment,
        payer_name: finalPayerName,
      };
      
      const response = await axios.post('/api/transactions', transactionData, {
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });

      const responseData = response.data.data;
      
      // Get fund account details for notifications
      const selectedFund = fundAccounts.find(fund => fund.id === parseInt(fundAccountId));
      
      // Process transaction and update balance
      try {
        const processed = await balanceService.processTransaction('RECEIVE_MONEY', {
          fund_account_id: parseInt(fundAccountId),
          amount: parseFloat(amount),
          payer: finalPayerName,
          fund_account_name: selectedFund?.name || `Fund Account #${fundAccountId}`,
          transaction_id: responseData.id || responseData.transaction_id,
          receipt_no: responseData.receipt_no
        });

        broadcastFundTransaction({
          accountId: parseInt(fundAccountId),
          type: 'collection',
          amount: parseFloat(amount),
          source: 'ReceiveMoney',
          balance: processed?.newBalance,
        });
      } catch (balanceError) {
        console.error('Balance update error:', balanceError);
        // Continue even if balance update fails
      }

      setSuccessMessage(`Collection recorded successfully! Receipt No: ${responseData.receipt_no}, Reference No: ${responseData.reference_no}`);
      
      // Reset form after short delay to show success message
      setTimeout(() => {
        resetForm();
      }, 3000);
      
    } catch (error) {
      console.error('Error creating transaction:', error);
      setMessage(error.response?.data?.message || 'Error creating transaction');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="receive-money-container">
      <div className="receive-money-form">
        {/* Header */}
        <div className="form-header">
          <h2><i className="fas fa-money-bill-wave"></i> Receive Money</h2>
        </div>

        {/* Success/Error Messages */}
        {successMessage && (
          <div className="alert alert-success">
            <i className="fas fa-check-circle"></i>
            {successMessage}
          </div>
        )}
        {message && (
          <div className="alert alert-error">
            <i className="fas fa-exclamation-triangle"></i>
            {message}
          </div>
        )}

        <form onSubmit={handleSubmit} className="enhanced-form">
          {/* Left Column - Receipt Information & Fund Assignment */}
          <div className="form-section left-column">
            {/* Receipt Information */}
            <div className="subsection-header">
              <h6><i className="fas fa-receipt"></i> Receipt Information</h6>
            </div>
            
            <div className="form-row">
              <div className="form-group">
                <label>Receipt Number</label>
                <div className="input-with-tooltip">
                  <input
                    type="text"
                    value={receiptNo || "Will auto-generate when form is filled"}
                    disabled
                    className="auto-generated-field"
                  />
                  <i className="fas fa-info-circle tooltip-icon" title="Auto-generated by the system for tracking"></i>
                </div>
              </div>
              
              <div className="form-group">
                <label>Reference Number</label>
                <div className="input-with-tooltip">
                  <input
                    type="text"
                    value={referenceNo || "Will auto-generate when form is filled"}
                    disabled
                    className="auto-generated-field"
                  />
                  <i className="fas fa-info-circle tooltip-icon" title="Auto-generated collection reference"></i>
                </div>
              </div>
            </div>
            {/* Payer Input */}
            <div className="form-group">
              <label>Payer Name <span className="required">*</span></label>
              <input
                type="text"
                placeholder="Enter payer's full name"
                value={payerName}
                onChange={(e) => {
                  setPayerName(e.target.value);
                  clearError('payerName');
                  generateReceiptNumbers();
                }}
                className={errors.payerName ? "error" : ""}
              />
              {errors.payerName && <span className="error-text">{errors.payerName}</span>}
            </div>
            
            <div className="form-group">
              <label>Fund Account <span className="required">*</span></label>
              <div className="selector-input" onClick={() => setShowFundAccountModal(true)}>
                <span className={selectedFundAccount ? "selected" : "placeholder"}>
                  {selectedFundAccount 
                    ? `${selectedFundAccount.name} (${selectedFundAccount.code}) - ${selectedFundAccount.account_type}` 
                    : "Click to select fund account"}
                </span>
                <i className="fas fa-chevron-down"></i>
              </div>
              {errors.fundAccount && <span className="error-text">{errors.fundAccount}</span>}
            </div>
          </div>

          {/* Right Column - Transaction Details */}
          <div className="form-section right-column">
            {/* Payer Information at TOP */}
         

            {/* Transaction Details */}
            <div className="subsection-header">
              <h6><i className="fas fa-coins"></i> Transaction Details</h6>
            </div>
            
            <div className="form-row">
              <div className="form-group">
                <label className="amount-label">Amount <span className="required">*</span></label>
                <input
                  type="number"
                  placeholder="0.00"
                  value={amount}
                  onChange={(e) => {
                    setAmount(e.target.value);
                    clearError('amount');
                  }}
                  className={`amount-input ${errors.amount ? "error" : ""}`}
                  min="0.01"
                  step="0.01"
                />
                {errors.amount && <span className="error-text">{errors.amount}</span>}
              </div>
              
              <div className="form-group">
                <label>Payment Mode</label>
                <select
                  value={modeOfPayment}
                  onChange={(e) => {
                    setModeOfPayment(e.target.value);
                    clearError('modeOfPayment');
                  }}
                  className={errors.modeOfPayment ? "error" : ""}
                >
                  <option value="Cash">Cash</option>
                  <option value="Cheque">Cheque</option>
                  <option value="Bank Transfer">Bank Transfer</option>
                  <option value="Online Payment">Online Payment</option>
                </select>
                {errors.modeOfPayment && <span className="error-text">{errors.modeOfPayment}</span>}
              </div>
            </div>

            <div className="form-group">
              <label>Reference (Optional)</label>
              <input
                type="text"
                placeholder="Enter reference number or details"
                value={reference}
                onChange={(e) => setReference(e.target.value)}
              />
            </div>

            <div className="form-group">
              <label>Description (Optional)</label>
              <textarea
                placeholder="Enter transaction description or notes"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                rows="3"
              />
            </div>
          </div>

          {/* Form Actions */}
          <div className="form-actions">
            <button
              type="button"
              onClick={resetForm}
              className="btn-secondary"
              disabled={loading}
            >
              <i className="fas fa-undo"></i>
              Reset
            </button>
            
            <button
              type="submit"
              className="btn-primary"
              disabled={loading}
            >
              {loading ? (
                <>
                  <i className="fas fa-spinner fa-spin"></i>
                  Processing...
                </>
              ) : (
                <>
                  <i className="fas fa-plus-circle"></i>
                  Create Collection Transaction
                </>
              )}
            </button>
          </div>
        </form>
      </div>

      {/* Fund Account Selection Modal */}
      {showFundAccountModal && (
        <div className="modal-overlay" onClick={() => setShowFundAccountModal(false)}>
          <div className="modal account-selector-modal" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h4><i className="fas fa-university"></i> Select Fund Account</h4>
              <button 
                className="close-button" 
                onClick={() => setShowFundAccountModal(false)}
              >
                ×
              </button>
            </div>
            
            <div className="modal-body">
              <div className="search-bar">
                <i className="fas fa-search"></i>
                <input
                  type="text"
                  placeholder="Search by account name or code..."
                  value={fundAccountSearch}
                  onChange={(e) => setFundAccountSearch(e.target.value)}
                />
              </div>
              
              <div className="accounts-grid">
                {filteredFundAccounts.length === 0 ? (
                  <div className="no-results">
                    <i className="fas fa-search"></i>
                    <p>No fund accounts found</p>
                  </div>
                ) : (
                  filteredFundAccounts.map((account) => (
                    <div
                      key={account.id}
                      className="account-card"
                      onClick={() => handleFundAccountSelect(account)}
                    >
                      <div className="account-info">
                        <h6>{account.name}</h6>
                        <p className="account-code">{account.code}</p>
                        <p className="account-type">{account.account_type}</p>
                        <p className="account-balance">Balance: ₱{parseFloat(account.balance || 0).toLocaleString()}</p>
                      </div>
                      <i className="fas fa-chevron-right"></i>
                    </div>
                  ))
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ReceiveMoney;
