import React, { useState, useEffect } from "react";
import "../../assets/admin.css";
import "./css/systemsettings.css";

const SystemSettings = () => {
  const [autoGenerateDailyEnabled, setAutoGenerateDailyEnabled] = useState(true);
  const [autoGenerateMonthlyEnabled, setAutoGenerateMonthlyEnabled] = useState(true);
  const [autoGenerateYearlyEnabled, setAutoGenerateYearlyEnabled] = useState(true);
  const [lastDailyGenDate, setLastDailyGenDate] = useState(null);
  const [lastMonthlyGenDate, setLastMonthlyGenDate] = useState(null);
  const [lastYearlyGenDate, setLastYearlyGenDate] = useState(null);

  useEffect(() => {
    // Load auto-generate settings from localStorage
    const savedDailyAutoGen = localStorage.getItem('dailyReportAutoGen');
    const savedMonthlyAutoGen = localStorage.getItem('monthlyReportAutoGen');
    const savedYearlyAutoGen = localStorage.getItem('yearlyReportAutoGen');
    const savedLastDailyDate = localStorage.getItem('dailyReportLastAutoGen');
    const savedLastMonthlyDate = localStorage.getItem('monthlyReportLastAutoGen');
    const savedLastYearlyDate = localStorage.getItem('yearlyReportLastAutoGen');
    
    console.log('Loading auto-gen settings:', {
      daily: savedDailyAutoGen,
      monthly: savedMonthlyAutoGen,
      yearly: savedYearlyAutoGen
    });
    
    // Daily
    if (savedDailyAutoGen === null) {
      setAutoGenerateDailyEnabled(true);
      localStorage.setItem('dailyReportAutoGen', 'true');
    } else {
      setAutoGenerateDailyEnabled(savedDailyAutoGen === 'true');
    }
    
    // Monthly
    if (savedMonthlyAutoGen === null) {
      setAutoGenerateMonthlyEnabled(true);
      localStorage.setItem('monthlyReportAutoGen', 'true');
    } else {
      setAutoGenerateMonthlyEnabled(savedMonthlyAutoGen === 'true');
    }
    
    // Yearly
    if (savedYearlyAutoGen === null) {
      setAutoGenerateYearlyEnabled(true);
      localStorage.setItem('yearlyReportAutoGen', 'true');
    } else {
      setAutoGenerateYearlyEnabled(savedYearlyAutoGen === 'true');
    }
    
    if (savedLastDailyDate) setLastDailyGenDate(savedLastDailyDate);
    if (savedLastMonthlyDate) setLastMonthlyGenDate(savedLastMonthlyDate);
    if (savedLastYearlyDate) setLastYearlyGenDate(savedLastYearlyDate);
  }, []);

  const toggleDailyAutoGenerate = () => {
    const newValue = !autoGenerateDailyEnabled;
    setAutoGenerateDailyEnabled(newValue);
    localStorage.setItem('dailyReportAutoGen', String(newValue));
  };

  const toggleMonthlyAutoGenerate = () => {
    const newValue = !autoGenerateMonthlyEnabled;
    setAutoGenerateMonthlyEnabled(newValue);
    localStorage.setItem('monthlyReportAutoGen', String(newValue));
  };

  const toggleYearlyAutoGenerate = () => {
    const newValue = !autoGenerateYearlyEnabled;
    setAutoGenerateYearlyEnabled(newValue);
    localStorage.setItem('yearlyReportAutoGen', String(newValue));
  };

  return (
    <div className="admin-page">
      <div className="card">
        <h2>System Settings</h2>
        <p>Configure application preferences and appearance.</p>

        <section className="settings-section">
          <h3>Appearance</h3>
          <div className="settings-group">
            <label htmlFor="mode-switcher">Theme</label>
            <div id="mode-switcher" className="theme-toggle">
              <input type="radio" name="theme" id="light" value="light" defaultChecked />
              <label htmlFor="light" className="toggle-option">Light</label>

              <input type="radio" name="theme" id="dark" value="dark" />
              <label htmlFor="dark" className="toggle-option">Dark</label>
            </div>
          </div>
        </section>

        <section className="settings-section">
          <h3>
            <i className="fas fa-robot"></i> Automatic Report Generation
          </h3>
          
          {/* Daily Reports */}
          <div className="settings-group auto-gen-setting">
            <div className="setting-info">
              <label className="setting-label">
                <i className="fas fa-calendar-day"></i> Auto-Generate Daily Reports
              </label>
              <p className="setting-description">
                Automatically generate daily reports at 11:59 PM every day
              </p>
            </div>
            <label className="toggle-switch">
              <input 
                type="checkbox" 
                checked={autoGenerateDailyEnabled}
                onChange={toggleDailyAutoGenerate}
              />
              <span className="toggle-slider"></span>
            </label>
          </div>

          {autoGenerateDailyEnabled && lastDailyGenDate && (
            <div className="last-gen-info-small">
              Last generated: {new Date(lastDailyGenDate).toLocaleDateString('en-US', { 
                year: 'numeric', 
                month: 'long', 
                day: 'numeric' 
              })}
            </div>
          )}

          {/* Monthly Reports */}
          <div className="settings-group auto-gen-setting">
            <div className="setting-info">
              <label className="setting-label">
                <i className="fas fa-calendar-alt"></i> Auto-Generate Monthly Reports
              </label>
              <p className="setting-description">
                Automatically generate monthly reports on the last day of each month at 11:59 PM
              </p>
            </div>
            <label className="toggle-switch">
              <input 
                type="checkbox" 
                checked={autoGenerateMonthlyEnabled}
                onChange={toggleMonthlyAutoGenerate}
              />
              <span className="toggle-slider"></span>
            </label>
          </div>

          {autoGenerateMonthlyEnabled && lastMonthlyGenDate && (
            <div className="last-gen-info-small">
              Last generated: {new Date(lastMonthlyGenDate).toLocaleDateString('en-US', { 
                year: 'numeric', 
                month: 'long' 
              })}
            </div>
          )}

          {/* Yearly Reports */}
          <div className="settings-group auto-gen-setting">
            <div className="setting-info">
              <label className="setting-label">
                <i className="fas fa-calendar"></i> Auto-Generate Yearly Reports
              </label>
              <p className="setting-description">
                Automatically generate yearly reports on December 31st at 11:59 PM
              </p>
            </div>
            <label className="toggle-switch">
              <input 
                type="checkbox" 
                checked={autoGenerateYearlyEnabled}
                onChange={toggleYearlyAutoGenerate}
              />
              <span className="toggle-slider"></span>
            </label>
          </div>

          {autoGenerateYearlyEnabled && lastYearlyGenDate && (
            <div className="last-gen-info-small">
              Last generated: {new Date(lastYearlyGenDate).toLocaleDateString('en-US', { 
                year: 'numeric' 
              })}
            </div>
          )}

          {/* Status Summary */}
          <div className="setting-status success">
            <i className="fas fa-info-circle"></i>
            <div>
              <strong>Active Auto-Generation:</strong>
              <ul style={{margin: '8px 0 0 0', paddingLeft: '20px'}}>
                {autoGenerateDailyEnabled && <li>Daily reports at 11:59 PM</li>}
                {autoGenerateMonthlyEnabled && <li>Monthly reports on last day of month at 11:59 PM</li>}
                {autoGenerateYearlyEnabled && <li>Yearly reports on December 31st at 11:59 PM</li>}
                {!autoGenerateDailyEnabled && !autoGenerateMonthlyEnabled && !autoGenerateYearlyEnabled && (
                  <li style={{color: '#d97706'}}>No auto-generation enabled</li>
                )}
              </ul>
            </div>
          </div>

          <div className="info-box">
            <p><strong>How it works:</strong></p>
            <ul>
              <li><strong>Daily:</strong> Generated at 11:59 PM every day</li>
              <li><strong>Monthly:</strong> Generated on the last day of each month at 11:59 PM</li>
              <li><strong>Yearly:</strong> Generated on December 31st at 11:59 PM</li>
              <li>Only one report per period is generated</li>
              <li>Reports include all transactions for that period</li>
              <li>Generated reports can be viewed in the respective History sections</li>
            </ul>
          </div>
        </section>
      </div>
    </div>
  );
};

export default SystemSettings;
