import React from 'react';
import { SkeletonLine, SkeletonCircle } from './LoadingSkeleton';

const ReportPageSkeleton = ({ isAdmin = true }) => {
  const tableHeadCells = ['REPORT ID', 'REPORT TYPE', 'GENERATED BY', 'ROLE', 'GENERATED AT', 'FORMAT', 'ACTIONS'];
  const tableRowCount = 10;

  return (
    <div className="generate-reports-page skeleton-generate-reports">
      {/* Header */}
      <div className="gr-header" style={{ border: '2px solid #000000', borderRadius: '8px' }}>
        <div className="gr-header-content">
          <h1 className="gr-title">
            <SkeletonLine width="320px" height={28} />
          </h1>
          <div className="gr-header-actions">
            <SkeletonLine width="200px" height={44} />
          </div>
        </div>
      </div>

      {/* KPI Sections - Only for Admin */}
      {isAdmin && (
        <>
          {/* DAILY KPI Section */}
          <div className="report-section">
            <div className="daily-kpi-container skeleton-card" style={{ border: '2px solid #000000', borderRadius: '8px', padding: '20px', background: '#ffffff', marginBottom: '20px' }}>
              <div className="daily-kpi-header" style={{ marginBottom: '20px' }}>
                <SkeletonLine width="400px" height={24} />
              </div>
              
              {/* KPI Metrics Cards */}
              <div className="daily-kpi-metrics" style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: '16px', marginBottom: '24px' }}>
                {Array.from({ length: 5 }).map((_, idx) => (
                  <div key={`metric-${idx}`} className="kpi-metric-card skeleton-card" style={{ border: '2px solid #e5e7eb', borderRadius: '8px', padding: '16px' }}>
                    <div className="metric-info">
                      <div className="metric-label" style={{ marginBottom: '8px' }}>
                        <SkeletonLine width="80%" height={14} />
                      </div>
                      <div className="metric-value">
                        <SkeletonLine width="90%" height={28} />
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              {/* Chart Section */}
              <div className="daily-chart-section" style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '20px' }}>
                {/* Left Summary Box */}
                <div className="daily-summary-box skeleton-card" style={{ border: '2px solid #e5e7eb', borderRadius: '8px', padding: '16px' }}>
                  <h4 style={{ marginBottom: '16px' }}>
                    <SkeletonLine width="150px" height={18} />
                  </h4>
                  
                  {/* Role Cards */}
                  <div className="role-cards-container" style={{ marginBottom: '16px', maxHeight: '250px', overflowY: 'auto', overflowX: 'hidden', paddingRight: '8px' }}>
                    {Array.from({ length: 3 }).map((_, idx) => (
                      <div key={`role-${idx}`} className="role-card skeleton-card" style={{ border: '1px solid #e5e7eb', borderRadius: '6px', padding: '12px', marginBottom: '12px' }}>
                        <SkeletonLine width="70%" height={16} style={{ marginBottom: '8px' }} />
                        <SkeletonLine width="50%" height={14} style={{ marginBottom: '6px' }} />
                        <SkeletonLine width="60%" height={14} />
                      </div>
                    ))}
                  </div>

                  {/* Summary Stats */}
                  <div className="summary-stats">
                    {Array.from({ length: 3 }).map((_, idx) => (
                      <div key={`stat-${idx}`} style={{ marginBottom: '10px' }}>
                        <SkeletonLine width="100%" height={14} />
                      </div>
                    ))}
                  </div>
                </div>

                {/* Right Chart Container */}
                <div className="daily-chart-container skeleton-card" style={{ border: '2px solid #e5e7eb', borderRadius: '8px', padding: '16px' }}>
                  <h4 style={{ marginBottom: '16px' }}>
                    <SkeletonLine width="300px" height={18} />
                  </h4>
                  <div className="chart-container" style={{ height: '300px' }}>
                    <SkeletonLine height="100%" />
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* MONTHLY KPI Section */}
          <div className="report-section">
            <div className="monthly-kpi-container skeleton-card" style={{ border: '2px solid #000000', borderRadius: '8px', padding: '20px', background: '#ffffff', marginBottom: '20px' }}>
              <div className="monthly-kpi-header" style={{ marginBottom: '20px' }}>
                <SkeletonLine width="400px" height={24} />
              </div>
              
              {/* Monthly Metrics */}
              <div className="monthly-kpi-metrics" style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '16px', marginBottom: '24px' }}>
                {Array.from({ length: 4 }).map((_, idx) => (
                  <div key={`monthly-metric-${idx}`} className="kpi-metric-card skeleton-card" style={{ border: '2px solid #e5e7eb', borderRadius: '8px', padding: '16px' }}>
                    <SkeletonLine width="80%" height={14} style={{ marginBottom: '8px' }} />
                    <SkeletonLine width="90%" height={28} />
                  </div>
                ))}
              </div>

              {/* Monthly Charts Grid */}
              <div className="monthly-charts-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '20px' }}>
                {Array.from({ length: 3 }).map((_, idx) => (
                  <div key={`monthly-chart-${idx}`} className="chart-card skeleton-card" style={{ border: '2px solid #e5e7eb', borderRadius: '8px', padding: '16px' }}>
                    <SkeletonLine width="70%" height={18} style={{ marginBottom: '16px' }} />
                    <div style={{ height: '250px' }}>
                      <SkeletonLine height="100%" />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* YEARLY KPI Section */}
          <div className="report-section">
            <div className="yearly-kpi-container skeleton-card" style={{ border: '2px solid #000000', borderRadius: '8px', padding: '20px', background: '#ffffff', marginBottom: '20px' }}>
              <div className="yearly-kpi-header" style={{ marginBottom: '20px' }}>
                <SkeletonLine width="400px" height={24} />
              </div>
              
              {/* Yearly Metrics */}
              <div className="yearly-kpi-metrics" style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: '16px', marginBottom: '24px' }}>
                {Array.from({ length: 5 }).map((_, idx) => (
                  <div key={`yearly-metric-${idx}`} className="kpi-metric-card skeleton-card" style={{ border: '2px solid #e5e7eb', borderRadius: '8px', padding: '16px' }}>
                    <SkeletonLine width="80%" height={14} style={{ marginBottom: '8px' }} />
                    <SkeletonLine width="90%" height={28} />
                  </div>
                ))}
              </div>

              {/* Yearly Charts Grid */}
              <div className="yearly-charts-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '20px' }}>
                {Array.from({ length: 3 }).map((_, idx) => (
                  <div key={`yearly-chart-${idx}`} className="chart-card skeleton-card" style={{ border: '2px solid #e5e7eb', borderRadius: '8px', padding: '16px' }}>
                    <SkeletonLine width="70%" height={18} style={{ marginBottom: '16px' }} />
                    <div style={{ height: '250px' }}>
                      <SkeletonLine height="100%" />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </>
      )}

      {/* Report Statistics Section */}
      <div className="gr-content-grid">
        <div className="report-stats-section">
          <div className="stats-grid">
            {/* Total Reports Card */}
            <div className="stat-card skeleton-card" style={{ border: '2px solid #000000', borderRadius: '8px', padding: '20px' }}>
              <div className="stat-icon" style={{ marginBottom: '12px' }}>
                <SkeletonCircle size={48} />
              </div>
              <div className="stat-content">
                <div className="stat-value" style={{ marginBottom: '8px' }}>
                  <SkeletonLine width="60px" height={32} />
                </div>
                <div className="stat-label">
                  <SkeletonLine width="100px" height={14} />
                </div>
              </div>
            </div>

            {/* Daily Reports Card */}
            <div className="stat-card skeleton-card" style={{ border: '2px solid #000000', borderRadius: '8px', padding: '20px' }}>
              <div className="stat-icon" style={{ marginBottom: '12px' }}>
                <SkeletonCircle size={48} />
              </div>
              <div className="stat-content">
                <div className="stat-value" style={{ marginBottom: '8px' }}>
                  <SkeletonLine width="60px" height={32} />
                </div>
                <div className="stat-label">
                  <SkeletonLine width="100px" height={14} />
                </div>
              </div>
            </div>

            {/* Monthly Reports Card */}
            <div className="stat-card skeleton-card" style={{ border: '2px solid #000000', borderRadius: '8px', padding: '20px' }}>
              <div className="stat-icon" style={{ marginBottom: '12px' }}>
                <SkeletonCircle size={48} />
              </div>
              <div className="stat-content">
                <div className="stat-value" style={{ marginBottom: '8px' }}>
                  <SkeletonLine width="60px" height={32} />
                </div>
                <div className="stat-label">
                  <SkeletonLine width="100px" height={14} />
                </div>
              </div>
            </div>

            {/* Yearly Reports Card */}
            <div className="stat-card skeleton-card" style={{ border: '2px solid #000000', borderRadius: '8px', padding: '20px' }}>
              <div className="stat-icon" style={{ marginBottom: '12px' }}>
                <SkeletonCircle size={48} />
              </div>
              <div className="stat-content">
                <div className="stat-value" style={{ marginBottom: '8px' }}>
                  <SkeletonLine width="60px" height={32} />
                </div>
                <div className="stat-label">
                  <SkeletonLine width="100px" height={14} />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Reports Table Section */}
      <div className="gr-reports-section">
        <div className="gr-reports-header">
          <div className="gr-section-title-group">
            <h3>
              <SkeletonLine width="280px" height={24} />
            </h3>
          </div>
          <div className="gr-header-controls">
            <div className="gr-search-filter-container">
              <div className="gr-date-filter-group">
                <SkeletonLine width="80px" height={14} style={{ marginBottom: '6px' }} />
                <SkeletonLine width="140px" height={40} />
              </div>
              
              <div className="gr-date-filter-group">
                <SkeletonLine width="80px" height={14} style={{ marginBottom: '6px' }} />
                <SkeletonLine width="140px" height={40} />
              </div>

              <div className="gr-account-search-container">
                <SkeletonLine width="260px" height={40} />
              </div>
              
              <div className="gr-filter-dropdown-container">
                <SkeletonLine width="200px" height={40} />
              </div>
            </div>
          </div>
        </div>

        <div className="gr-table-section">
          <div className="gr-table-container">
            <table className="gr-table">
              <thead>
                <tr>
                  {tableHeadCells.map((cell, idx) => (
                    <th key={`head-${idx}`}>
                      <SkeletonLine width="80%" height={14} />
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {Array.from({ length: tableRowCount }).map((_, rowIndex) => (
                  <tr key={`row-${rowIndex}`} className="gr-table-row">
                    {tableHeadCells.map((cell, cellIndex) => (
                      <td key={`cell-${rowIndex}-${cellIndex}`}>
                        <div className="gr-cell-content">
                          {cellIndex === 0 ? (
                            // Report ID
                            <span className="gr-report-id">
                              <SkeletonLine width="60px" height={16} />
                            </span>
                          ) : cellIndex === 1 ? (
                            // Report Type
                            <span className="gr-report-type">
                              <SkeletonLine width="80px" height={16} />
                            </span>
                          ) : cellIndex === 2 ? (
                            // Generated By
                            <span className="gr-generated-by">
                              <SkeletonLine width="120px" height={16} />
                            </span>
                          ) : cellIndex === 3 ? (
                            // Role
                            <span className="gr-generated-role">
                              <SkeletonLine width="70px" height={16} />
                            </span>
                          ) : cellIndex === 4 ? (
                            // Generated At
                            <span className="gr-generated-at">
                              <SkeletonLine width="100px" height={16} />
                            </span>
                          ) : cellIndex === 5 ? (
                            // Format
                            <span className="gr-format-badge">
                              <SkeletonLine width="50px" height={16} />
                            </span>
                          ) : (
                            // Actions
                            <div className="gr-action-buttons-group">
                              <SkeletonLine width="40px" height={32} />
                            </div>
                          )}
                        </div>
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Pagination */}
          <div className="gr-table-pagination">
            <div className="gr-pagination-info">
              <SkeletonLine width="180px" height={16} />
            </div>
            <div className="gr-pagination-controls">
              <SkeletonLine width="80px" height={36} style={{ marginRight: '12px' }} />
              <SkeletonLine width="100px" height={16} style={{ marginRight: '12px' }} />
              <SkeletonLine width="80px" height={36} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportPageSkeleton;
