import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const normalizeAmount = (value) => {
  if (value === null || value === undefined) return null;
  if (typeof value === 'number') return Number.isNaN(value) ? null : value;
  if (typeof value === 'string') {
    const cleaned = value.replace(/[^0-9.-]/g, '');
    if (!cleaned.trim()) return null;
    const parsed = parseFloat(cleaned);
    return Number.isNaN(parsed) ? null : parsed;
  }
  return null;
};

const defaultFormatCurrency = (value) => {
  const amount = normalizeAmount(value);
  if (amount === null) return '—';
  return `PHP ${Math.abs(amount).toLocaleString('en-PH', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
};

const formatDate = (value) => {
  if (!value) return '—';
  try {
    return new Intl.DateTimeFormat('en-PH', {
      year: 'numeric',
      month: 'short',
      day: '2-digit',
    }).format(new Date(value));
  } catch (e) {
    return value;
  }
};

export const generateChequePDF = ({
  filters = {},
  cheques = [],
  summary = {},
  generatedBy = 'System',
  reportTitle = 'Issued Cheques Report',
  formatCurrency,
}) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  const centerX = pageWidth / 2;
  const fmt = formatCurrency || defaultFormatCurrency;

  const addHeader = () => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text(reportTitle, centerX, 18, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.text(`Generated on: ${formatDate(new Date().toISOString())}`, centerX, 26, { align: 'center' });
    doc.text(`Generated by: ${generatedBy}`, centerX, 32, { align: 'center' });
  };

  const addFilters = () => {
    const filterEntries = Object.entries(filters)
      .filter(([, v]) => v !== undefined && v !== null && v !== '')
      .map(([k, v]) => `${k}: ${v}`);
    if (!filterEntries.length) return;

    doc.setFontSize(11);
    doc.text('Applied Filters:', margin, 40);
    doc.setFontSize(10);

    const perRow = 3;
    filterEntries.forEach((entry, idx) => {
      const row = Math.floor(idx / perRow);
      const col = idx % perRow;
      const x = margin + col * 60;
      const y = 46 + row * 6;
      doc.text(`• ${entry}`, x, y);
    });
  };

  const addSummary = () => {
    const totalCheques = summary.totalCheques ?? cheques.length ?? 0;
    const totalAmount = summary.totalAmount ?? 0;
    const averageAmount = summary.averageAmount ?? 0;

    const summaryRows = [
      ['Total Cheques', String(totalCheques)],
      ['Total Amount', fmt(totalAmount)],
      ['Average Amount', fmt(averageAmount)],
    ];

    autoTable(doc, {
      startY: 60,
      head: [['Metric', 'Value']],
      body: summaryRows,
      styles: { fontSize: 9 },
      headStyles: { fillColor: [0, 0, 0], textColor: 255 },
      columnStyles: {
        0: { cellWidth: 60 },
        1: { cellWidth: 60 },
      },
      margin: { left: margin, right: margin },
    });
  };

  const addChequesTable = () => {
    if (!cheques.length) {
      const y = doc.lastAutoTable?.finalY ? doc.lastAutoTable.finalY + 16 : 90;
      doc.setFontSize(12);
      doc.text('No cheques found for the selected filters.', margin, y);
      return;
    }

    const body = cheques.map((cheque, index) => [
      String(index + 1),
      cheque.cheque_number || '—',
      formatDate(cheque.issue_date || cheque.created_at),
      cheque.payee_name || '—',
      normalizeAmount(cheque.amount), // raw value; formatted in willDrawCell
      cheque.status || 'Issued',
      cheque.reconciled ? 'Reconciled' : 'Unmatched',
    ]);

    autoTable(doc, {
      startY: doc.lastAutoTable?.finalY ? doc.lastAutoTable.finalY + 14 : 90,
      head: [[
        '#',
        'Cheque No.',
        'Issue Date',
        'Payee Name',
        'Amount',
        'Status',
        'Reconciliation',
      ]],
      body,
      styles: { fontSize: 9, halign: 'left' },
      headStyles: { fillColor: [0, 0, 0], textColor: 255 },
      columnStyles: {
        0: { cellWidth: 10, halign: 'center' }, // #
        1: { cellWidth: 28 }, // Cheque No.
        2: { cellWidth: 28 }, // Issue Date
        3: { cellWidth: 73 }, // Payee Name (45 + 28 from Bank)
        4: { cellWidth: 35, halign: 'right' }, // Amount
        5: { cellWidth: 22 }, // Status
        6: { cellWidth: 28 }, // Reconciliation
      },
      margin: { left: margin, right: margin },
      didDrawPage: (data) => {
        const pageNumber = doc.internal.getNumberOfPages();
        doc.setFontSize(9);
        doc.text(`Page ${data.pageNumber} of ${pageNumber}`,
          centerX,
          pageHeight - 10,
          { align: 'center' }
        );
      },
      willDrawCell: (data) => {
        // Amount column is now at index 4
        if (data.section === 'body' && data.column.index === 4) {
          data.cell.text = [fmt(data.cell.raw)];
        }
      },
      pageBreak: 'auto',
    });
  };

  addHeader();
  addFilters();
  addSummary();
  addChequesTable();

  const filename = `${reportTitle.replace(/\s+/g, '_').toLowerCase()}_${new Date().toISOString().split('T')[0]}.pdf`;
  const blob = doc.output('blob');

  return { blob, filename };
};

export default generateChequePDF;

