import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';


// Generate a Disbursement PDF and return a Blob + filename for preview/download
// Params:
// - disbursementsForExport: Array<{ id, reference, recipient, amount, mode_of_payment, created_at }>
// - disbursementSummary: { totalCount, totalAmount, averageAmount }
// - filters: { startDate?: string, endDate?: string }
// - formatCurrency: (n:number)=>string
export function generateDisbursementPDF({ disbursementsForExport = [], disbursementSummary, filters = {}, formatCurrency }) {
  // Create PDF document
  const doc = new jsPDF('p', 'mm', 'a4');
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let y = 15;

  const generatedBy = (typeof window !== 'undefined' && localStorage.getItem('user_name')) || 'System';
  const generatedTime = new Date().toLocaleString();
  const dateRange = (filters.startDate && filters.endDate)
    ? `${filters.startDate} to ${filters.endDate}`
    : 'All Dates';

  // Header (top right timestamp)
  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);
  doc.text(`Generated: ${generatedTime}`, pageWidth - 15, y, { align: 'right' });
  y += 8;

  // Title
  doc.setFontSize(16);
  doc.text('Recent Disbursements Report', pageWidth / 2, y, { align: 'center' });
  y += 7;

  // Subtitles
  doc.setFontSize(11);
  doc.text(`Generated By: ${generatedBy}`, pageWidth / 2, y, { align: 'center' });
  y += 6;
  doc.text(dateRange, pageWidth / 2, y, { align: 'center' });
  y += 10;

  // Summary
  doc.setFontSize(11);
  doc.text(`Total Disbursements: ${disbursementSummary?.totalCount ?? 0}`, 15, y); y += 6;
  doc.text(`Total Amount: PHP ${formatCurrency ? formatCurrency(disbursementSummary?.totalAmount ?? 0) : `${(disbursementSummary?.totalAmount ?? 0)}`}`, 15, y); y += 6;
  doc.text(`Average Amount: PHP ${formatCurrency ? formatCurrency(disbursementSummary?.averageAmount ?? 0) : `${(disbursementSummary?.averageAmount ?? 0)}`}`, 15, y); y += 10;

  // Section title
  doc.text('Disbursements', 15, y); y += 6;

  const body = (disbursementsForExport || []).map((d) => [
    `#${d.id}`,
    d.reference,
    d.recipient,
    formatCurrency ? formatCurrency(d.amount) : d.amount,
    d.mode_of_payment,
    d.created_at ? new Date(d.created_at).toLocaleDateString() : 'N/A'
  ]);

  // Table
  autoTable(doc, {
    startY: y,
    head: [['Disbursement ID', 'Reference', 'Recipient', 'Amount', 'Payment Mode', 'Date']],
    body,
    theme: 'grid',
    headStyles: {
      fillColor: [0, 0, 0],
      textColor: [255, 255, 255],
      fontStyle: 'normal',
      fontSize: 10,
      halign: 'left',
      valign: 'middle'
    },
    bodyStyles: {
      textColor: [0, 0, 0],
      fontSize: 9,
      halign: 'left',
      valign: 'middle'
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251]
    },
    margin: { top: 10, right: 15, bottom: 20, left: 15 },
    columnStyles: {
      0: { halign: 'center', cellWidth: 25 },
      1: { halign: 'left', cellWidth: 35 },
      2: { halign: 'left', cellWidth: 30 },
      3: { halign: 'right', cellWidth: 40 },
      4: { halign: 'center', cellWidth: 25 },
      5: { halign: 'center', cellWidth: 25 }
    },
    didDrawPage: (data) => {
      // Footer: page numbering
      const pageCount = doc.getNumberOfPages();
      doc.setFontSize(9);
      doc.setTextColor(128, 128, 128);
      doc.text(`Page ${data.pageNumber} of ${pageCount}`, pageWidth - 15, pageHeight - 8, { align: 'right' });
    }
  });

  // Filename
  let filename = `Disbursement_${new Date().toISOString().split('T')[0]}`;
  if (filters.startDate && filters.endDate) filename = `Disbursement_${filters.startDate}_to_${filters.endDate}`;
  else if (filters.startDate) filename = `Disbursement_from_${filters.startDate}`;
  else if (filters.endDate) filename = `Disbursement_to_${filters.endDate}`;

  const blob = doc.output('blob');
  return { blob, filename: `${filename}.pdf` };
}

