import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// Generate an Override Requests PDF and return a Blob + filename for preview/download
// Params:
// - overrideRequests: Array<{ id, transaction_id, requested_by, reason, status, created_at }>
// - filters: { dateFrom?: string, dateTo?: string, status?: string }
export function generateOverridePDF({ overrideRequests = [], filters = {} }) {
  // Create PDF document
  const doc = new jsPDF('p', 'mm', 'a4');
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let y = 15;

  const generatedBy = (typeof window !== 'undefined' && localStorage.getItem('user_name')) || 'System';
  const generatedTime = new Date().toLocaleString();
  
  // Calculate date range text
  let dateRange = 'Date Range: All Dates';
  if (filters.dateFrom && filters.dateTo) {
    dateRange = `Date Range: ${new Date(filters.dateFrom).toLocaleDateString()} to ${new Date(filters.dateTo).toLocaleDateString()}`;
  } else if (filters.dateFrom) {
    dateRange = `Date Range: From ${new Date(filters.dateFrom).toLocaleDateString()}`;
  } else if (filters.dateTo) {
    dateRange = `Date Range: Until ${new Date(filters.dateTo).toLocaleDateString()}`;
  }

  // Header (top right timestamp)
  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);
  doc.text(`Generated: ${generatedTime}`, pageWidth - 15, y, { align: 'right' });
  y += 8;

  // Title
  doc.setFontSize(16);
  doc.text('Override Requests Report', pageWidth / 2, y, { align: 'center' });
  y += 7;

  // Subtitles
  doc.setFontSize(11);
  doc.text(`Generated By: ${generatedBy}`, pageWidth / 2, y, { align: 'center' });
  y += 6;
  doc.text(dateRange, pageWidth / 2, y, { align: 'center' });
  y += 10;

  // Summary
  const pendingCount = overrideRequests.filter(r => r.status === 'pending').length;
  const approvedCount = overrideRequests.filter(r => r.status === 'approved').length;
  const rejectedCount = overrideRequests.filter(r => r.status === 'rejected').length;

  doc.setFontSize(11);
  doc.text(`Total Requests: ${overrideRequests.length}`, 15, y); y += 6;
  doc.text(`Pending: ${pendingCount}`, 15, y); y += 6;
  doc.text(`Approved: ${approvedCount}`, 15, y); y += 6;
  doc.text(`Rejected: ${rejectedCount}`, 15, y); y += 10;

  // Section title
  doc.text('Override Requests', 15, y); y += 6;

  const body = (overrideRequests || []).map((req) => [
    `#${req.id}`,
    `#${req.transaction_id}`,
    req.requested_by?.name || 'N/A',
    req.requested_by?.role || req.requestedBy?.role || 'N/A',
    req.reason || 'N/A',
    req.status || 'N/A',
    req.created_at ? new Date(req.created_at).toLocaleDateString() : 'N/A'
  ]);

  // Table
  autoTable(doc, {
    startY: y,
    head: [['ID', 'Transaction', 'Requested By', 'Role', 'Reason', 'Status', 'Date']],
    body,
    theme: 'grid',
    headStyles: {
      fillColor: [0, 0, 0],
      textColor: [255, 255, 255],
      fontStyle: 'normal',
      fontSize: 10,
      halign: 'left',
      valign: 'middle'
    },
    bodyStyles: {
      textColor: [0, 0, 0],
      fontSize: 9,
      halign: 'left',
      valign: 'middle'
    },
    alternateRowStyles: {
      fillColor: [255, 255, 255]
    },
    margin: { top: 10, right: 15, bottom: 20, left: 15 },
    columnStyles: {
      0: { halign: 'center', cellWidth: 18 },
      1: { halign: 'center', cellWidth: 25 },
      2: { halign: 'left', cellWidth: 28 },
      3: { halign: 'left', cellWidth: 22 },
      4: { halign: 'left', cellWidth: 32 },
      5: { halign: 'center', cellWidth: 18 },
      6: { halign: 'center', cellWidth: 22 }
    },
    didDrawPage: (data) => {
      // Footer: page numbering
      const pageCount = doc.getNumberOfPages();
      doc.setFontSize(9);
      doc.setTextColor(128, 128, 128);
      doc.text(`Page ${data.pageNumber} of ${pageCount}`, pageWidth - 15, pageHeight - 8, { align: 'right' });
    }
  });

  // Filename
  let filename = `Override_Requests_${new Date().toISOString().split('T')[0]}`;
  if (filters.dateFrom && filters.dateTo) {
    filename = `Override_Requests_${new Date(filters.dateFrom).toISOString().split('T')[0]}_to_${new Date(filters.dateTo).toISOString().split('T')[0]}`;
  } else if (filters.dateFrom) {
    filename = `Override_Requests_from_${new Date(filters.dateFrom).toISOString().split('T')[0]}`;
  } else if (filters.dateTo) {
    filename = `Override_Requests_to_${new Date(filters.dateTo).toISOString().split('T')[0]}`;
  }

  const blob = doc.output('blob');
  return { blob, filename: `${filename}.pdf` };
}
