import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const formatDate = (value) => {
  if (!value) return '—';
  try {
    return new Intl.DateTimeFormat('en-PH', {
      year: 'numeric', month: 'short', day: '2-digit',
    }).format(new Date(value));
  } catch {
    return String(value);
  }
};

export const generateStaffDirectoryPDF = ({
  staff = [],
  filters = {},
  generatedBy = 'System',
  reportTitle = 'Staff Directory',
}) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const centerX = pageWidth / 2;
  const margin = 14;

  // Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(`${reportTitle} Report`, centerX, 18, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(`Generated on: ${formatDate(new Date().toISOString())}`, centerX, 26, { align: 'center' });
  doc.text(`Generated by: ${generatedBy}`, centerX, 32, { align: 'center' });

  // Filters summary
  const filterEntries = Object.entries(filters)
    .filter(([, v]) => v !== undefined && v !== null && v !== '')
    .map(([k, v]) => `${k}: ${v}`);
  if (filterEntries.length) {
    doc.setFontSize(11);
    doc.text('Applied Filters:', margin, 40);
    doc.setFontSize(10);
    const perRow = 3;
    filterEntries.forEach((entry, idx) => {
      const row = Math.floor(idx / perRow);
      const col = idx % perRow;
      const x = margin + col * 60;
      const y = 46 + row * 6;
      doc.text(`• ${entry}`, x, y);
    });
  }

  // Table
  const body = staff.map((s, i) => [
    String(i + 1),
    s.name || '—',
    s.email || '—',
    s.role || '—',
    (s.status || '').toString().toUpperCase() || '—',
    formatDate(s.joinDate),
  ]);

  autoTable(doc, {
    startY: 60,
    head: [['#', 'Name', 'Email', 'Role', 'Status', 'Join Date']],
    body,
    styles: { fontSize: 9, halign: 'left' },
    headStyles: { fillColor: [0, 0, 0], textColor: 255 },
    columnStyles: {
      0: { cellWidth: 8, halign: 'center' },
      1: { cellWidth: 42 },
      2: { cellWidth: 56 },
      3: { cellWidth: 24 },
      4: { cellWidth: 24 },
      5: { cellWidth: 28 },
    },
    margin: { left: margin, right: margin },
    didDrawPage: (data) => {
      const pageNumber = doc.internal.getNumberOfPages();
      doc.setFontSize(9);
      doc.text(`Page ${data.pageNumber} of ${pageNumber}`,
        centerX, pageHeight - 10, { align: 'center' });
    },
  });

  const filename = `staff_directory_${new Date().toISOString().split('T')[0]}.pdf`;
  const blob = doc.output('blob');
  return { blob, filename };
};

export default generateStaffDirectoryPDF;
